name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  $CHANGES
change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "No changes."
version-resolver:
  default: patch
